"""Strongest-arguments summary for a claim, generated by Claude.

Called only when a new response is submitted (see routes.respond) — the
result is cached on the claims row and served on page load without
another API call. See db.update_claim_summary.
"""

import json

import anthropic

MODEL = "claude-haiku-4-5"

SYSTEM_PROMPT = (
    "You summarize a debate for a 'structured disagreement' site. Given a claim and "
    "a list of reader responses tagged agree/disagree, write the strongest argument "
    "synthesis for each side in 1-2 plain sentences. Base each summary only on the "
    "responses given for that side. If a side has no responses, use exactly the text "
    "'No arguments submitted yet.' for that side."
)

OUTPUT_SCHEMA = {
    "type": "object",
    "properties": {
        "agree_summary": {"type": "string"},
        "disagree_summary": {"type": "string"},
    },
    "required": ["agree_summary", "disagree_summary"],
    "additionalProperties": False,
}

FALLBACK_SUMMARY = {
    "agree_summary": "Summary temporarily unavailable.",
    "disagree_summary": "Summary temporarily unavailable.",
}


def _format_responses(responses, side):
    matching = [r["body"] for r in responses if r["side"] == side]
    if not matching:
        return "(none)"
    return "\n".join(f"- {body}" for body in matching)


def generate_summary(claim_text, responses):
    user_content = (
        f"Claim: {claim_text}\n\n"
        f"Agree responses:\n{_format_responses(responses, 'agree')}\n\n"
        f"Disagree responses:\n{_format_responses(responses, 'disagree')}"
    )

    try:
        client = anthropic.Anthropic()
        response = client.messages.create(
            model=MODEL,
            max_tokens=512,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_content}],
            output_config={"format": {"type": "json_schema", "schema": OUTPUT_SCHEMA}},
        )
    except anthropic.APIError:
        return FALLBACK_SUMMARY

    text = next((b.text for b in response.content if b.type == "text"), None)
    if not text:
        return FALLBACK_SUMMARY

    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        return FALLBACK_SUMMARY

    return {
        "agree_summary": data.get("agree_summary") or "No arguments submitted yet.",
        "disagree_summary": data.get("disagree_summary") or "No arguments submitted yet.",
    }
